/**
 * Reads root `.env` and writes `src/app/env/generated-env.local.ts` (gitignored).
 * Never commit secrets; only variable names appear in `.env.example`.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const envPath = join(root, '.env');
const outDir = join(root, 'src', 'app', 'env');
const outFile = join(outDir, 'generated-env.local.ts');

const keys = [
  'NG_APP_GEMINI_API_KEY',
  'NG_APP_GEMINI_MODEL',
  'NG_APP_FIREBASE_API_KEY',
  'NG_APP_FIREBASE_AUTH_DOMAIN',
  'NG_APP_FIREBASE_PROJECT_ID',
  'NG_APP_FIREBASE_STORAGE_BUCKET',
  'NG_APP_FIREBASE_MESSAGING_SENDER_ID',
  'NG_APP_FIREBASE_APP_ID'
];

function parseDotEnv(text) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const eq = t.indexOf('=');
    if (eq <= 0) continue;
    const k = t.slice(0, eq).trim();
    let v = t.slice(eq + 1).trim();
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
      v = v.slice(1, -1);
    }
    out[k] = v;
  }
  return out;
}

function esc(s) {
  return JSON.stringify(s ?? '');
}

let bag = {};
if (existsSync(envPath)) {
  try {
    bag = parseDotEnv(readFileSync(envPath, 'utf8'));
  } catch (e) {
    console.warn('[gen-env] Failed to read .env:', e);
  }
}

mkdirSync(outDir, { recursive: true });

const lines = [
  '/** AUTO-GENERATED by scripts/gen-env.mjs — do not edit. Run `npm run env:sync` after changing `.env`. */',
  ''
];
for (const k of keys) {
  lines.push(`export const ${k} = ${esc(bag[k] ?? '')};`);
}
lines.push('');
lines.push(`export const NG_APP_ENV_LOADED_AT = ${esc(new Date().toISOString())};`);
lines.push('');

writeFileSync(outFile, lines.join('\n'), 'utf8');
console.log('[gen-env] Wrote', outFile);
